# config/config.yaml

# 路径配置
paths:
  raw: "data/raw"
  processed: "data/processed"
  results: "results"
  scripts: "scripts"
  models: "data/models"
  trf_binary: "/homeb/xuminghua/trepp/scripts/trf-4.10.0"  # 指向你的 TRF 可执行文件
  
processed:
  db: "data/processed/genome_annotations.db"
  train_features: "data/processed/train_features.csv"
  eval_features: "data/processed/eval_features.csv"



# 参考基因组
reference:
  fasta: "data/raw/hg19.fa"

# 输入数据
datasets:
  train: "data/raw/train.sorted.bed"
  eval: "data/raw/eval.sorted.bed"

# 基因组注释文件 (对应 data/raw 下的文件名)
annotations:
  3utr: "3UTR.sorted.merged.appended.bed"
  5utr: "5UTR.sorted.merged.appended.bed"
  exon: "exon.sorted.merged.appended.bed"
  intron: "intron.sorted.merged.appended.bed"
  start_codon: "start_codon.sorted.merged.appended.bed"
  stop_codon: "stop_codon.sorted.merged.appended.bed"
  cpg: "cpg_island.sorted.bed"
  ctcf: "ctcf.sorted.bed"
  gnomad: "data/raw/gnomad.v2.1.1.lof_metrics.by_gene.txt"
  gff: "data/raw/gencode.v49lift37.annotation.gff3"

# 实验参数
params:
  flank_size: 1000  # 侧翼序列长度
  kmer_size: 4      # K-mer 特征
  models_to_compare: ["TREPP_Stacking", "RandomForest", "SVM", "XGBoost_Base", "MLP"]
  # TRF 参数: Match Mismatch Delta PM PI MinScore MaxPeriod
  # 论文参数: "2 7 80 10 30 2000 -L 2 -H" (注意：-L -H 是格式控制)
  trf_cmd: "2 7 80 10 30 2000 -h -ngs"